apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: topic-reco-trainer-stag
  namespace: staging
  labels:
    project: topic-recommender-v1
    service: data_trainer
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: credentials
            secret:
              secretName: topicreco-legacytrainer-service-account
          containers:
          - name: reco-cron-staging
            volumeMounts:
            - name: credentials
              mountPath: /secrets
              readOnly: true
            image: gcr.io/kumparan-data/reco-cron-staging:v0.1.X
            imagePullPolicy: Always
            resources:
              requests:
                memory: 8192Mi
              limits:
                memory: 8192Mi
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/secrets/topic-recommender-staging.json"
              - name: STACKDRIVER_LOGGING_ENABLED
                value: "1"
          restartPolicy: Never
