apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: topic-reco-dailytrainer-prod
  namespace: production
  labels:
    project: topic-recommender-v1
    service: data_trainer
spec:
  schedule: "*/50 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: credentials
            secret:
              secretName: topicreco-legacytrainer-service-account
          containers:
          - name: reco-dailycron-production
            volumeMounts:
            - name: credentials
              mountPath: /secrets
              readOnly: true
            image: gcr.io/kumparan-data/reco-dailycron-production:v0.1.X
            imagePullPolicy: Always
            resources:
              requests:
                memory: 1024Mi
              limits:
                memory: 2048Mi
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/secrets/topic-recommender-staging.json"
              - name: STACKDRIVER_LOGGING_ENABLED
                value: "1"
          restartPolicy: Never

