apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: topic-reco-dailytrainer-stag
  namespace: staging
  labels:
    project: topic-recommender-v1
    service: data_trainer
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reco-dailycron-staging
            image: gcr.io/kumparan-data/reco-dailycron-staging:v0.1.X
            imagePullPolicy: Always
            resources:
              requests:
                memory: 2048Mi
              limits:
                memory: 1024Mi
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                valueFrom:
                  secretKeyRef:
                    key: GOOGLE_APPLICATION_CREDENTIALS
                    name: topicreco-legacytrainer-service-account
              - name: STACKDRIVER_LOGGING_ENABLED
                value: "1"
          restartPolicy: Never
